[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.10.0"
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
ethereum = { version = "0.12.0", default-features = false, features = ["with-serde"] }
ethereum-types = "0.13.1"
web3 = "0.17.0"
ethabi = "17.0.0"

sha3 = { version = "0.10", default-features = false }
rlp = { version = "0.5", default-features = false }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"], optional = true }
rust-embed = "5.7.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"

hex = "0.4"
clap = "2.32"
libsecp256k1 = "0.7"
parity-bytes = "0.1"
